public enum GameStates
{
    APP_STARTED,
    REQUIRE_START_PLAY,
    PLAYING,
    PAUSE,
    REQUIRE_PLAYING_END_CLIP,
    PLAYING_END_CLIP,
    NOT_PLAYING,
    REQUIRE_RESTART,
    REQUIRE_PLAYING_RESTART_CLIP,
    PLAYING_RESTART_CLIP,
    REQUIRE_RESTART_CYLINDER_MANAGER,
    REQUIRE_PLAYING_START_CLIP,
    PLAYING_START_CLIP,
    REQUIRE_START_CYLINDER_MANAGER,
    PLAYING_ROOF_FALLING_CLIP
}
